#############################################################
# ____        _             _   ____                      _ #
#/ ___| _ __ (_) __ _  ___ | |_| __ )  ___   __ _ _ __ __| |#
#\___ \| '_ \| |/ _` |/ _ \| __|  _ \ / _ \ / _` | '__/ _` |#
# ___) | |_) | | (_| | (_) | |_| |_) | (_) | (_| | | | (_| |#
#|____/| .__/|_|\__, |\___/ \__|____/ \___/ \__,_|_|  \__,_|#
#      |_|      |___/                                       #
#############################################################
#
# Report issues: https://github.com/yPedx/SpigotBoard/issues
# Timezones: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
#

Settings:
  update-interval-seconds: 1
  toggle-command: 'scoreboard'
  timezone: 'America/New_York'
  time-format: 'HH:mm a'
  update-checker: true
  disable-stats: false
  disabled-worlds:
    - 'disabled-world-1'
    - 'disabled-world-2'

Scoreboard:
  title: '     &c&lSpigot&7&lBoard 3.0.4     '
  text:
    - ' '
    - '&8» &cPlayer'
    - '&7{player}'
    - ''
    - '&8» &cPlayers online'
    - '&7{online-players}/{max-players}'
    - ''
    - '&8» &cLocation'
    - '&cx: &7{x} &cy: &7{y} &cz: &7{z}'
    - ''
    - '&8» &cTime'
    - '&7{time}'